//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artwork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artwork()
        {
            this.Artwork_Gallery = new HashSet<Artwork_Gallery>();
            this.Artwork_Tag = new HashSet<Artwork_Tag>();
            this.Auctions = new HashSet<Auction>();
            this.Order_Item = new HashSet<Order_Item>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int artwork_id { get; set; }
        public Nullable<int> artist_id { get; set; }
        public string artwork_name { get; set; }
        public string artwork_image { get; set; }
        public string artwork_description { get; set; }
        public string artwork_price { get; set; }
        public string artwork_dimensions { get; set; }
        public string artwork_date { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> artwork_status { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artwork_Gallery> Artwork_Gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artwork_Tag> Artwork_Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auction> Auctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
