//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction_User
    {
        public int auction_user_id { get; set; }
        public Nullable<int> auction_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string auction_amount { get; set; }
        public string auction_user_created_date { get; set; }
    
        public virtual Auction Auction { get; set; }
        public virtual User User { get; set; }
    }
}
