//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibition
    {
        public int exhibition_id { get; set; }
        public string exhibition_name { get; set; }
        public string exhibition_location { get; set; }
        public string exhibition_image { get; set; }
        public string exhibition_description { get; set; }
        public string exhibition_start_date { get; set; }
        public string exhibition_end_date { get; set; }
    }
}
