//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exhibition()
        {
            this.Exhibition_Gallery = new HashSet<Exhibition_Gallery>();
        }
    
        public int exhibition_id { get; set; }
        public string exhibition_name { get; set; }
        public string exhibition_location { get; set; }
        public string exhibition_image { get; set; }
        public string exhibition_description { get; set; }
        public string exhibition_start_date { get; set; }
        public string exhibition_end_date { get; set; }
        public Nullable<bool> exhibition_is_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exhibition_Gallery> Exhibition_Gallery { get; set; }
    }
}
