//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gallery()
        {
            this.Artwork_Gallery = new HashSet<Artwork_Gallery>();
        }
    
        public int gallery_id { get; set; }
        public string gallery_name { get; set; }
        public string gallery_image { get; set; }
        public string gallery_description { get; set; }
        public Nullable<bool> gellery_is_active { get; set; }
        public string gallery_created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artwork_Gallery> Artwork_Gallery { get; set; }
    }
}
