//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GalleryArtEntities : DbContext
    {
        public GalleryArtEntities()
            : base("name=GalleryArtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Artwork> Artworks { get; set; }
        public virtual DbSet<Artwork_Gallery> Artwork_Gallery { get; set; }
        public virtual DbSet<Artwork_Tag> Artwork_Tag { get; set; }
        public virtual DbSet<Auction> Auctions { get; set; }
        public virtual DbSet<Auction_User> Auction_User { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Exhibition> Exhibitions { get; set; }
        public virtual DbSet<Exhibition_Gallery> Exhibition_Gallery { get; set; }
        public virtual DbSet<Favourite> Favourites { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Order_Item> Order_Item { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
