//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notification_id { get; set; }
        public Nullable<int> notification_recipient_id { get; set; }
        public Nullable<int> notification_sender_id { get; set; }
        public string notification_title { get; set; }
        public string notification_message { get; set; }
        public Nullable<bool> notification_is_read { get; set; }
        public string notificaiton_click_url { get; set; }
        public string notification_created_date { get; set; }
        public Nullable<int> artwork_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
