//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        public int order_item_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> artwork_id { get; set; }
        public string price { get; set; }
    
        public virtual Artwork Artwork { get; set; }
        public virtual Order Order { get; set; }
    }
}
