//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineArtGallery.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Item = new HashSet<Order_Item>();
        }
    
        public int order_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string order_total { get; set; }
        public string order_created_date { get; set; }
        public string order_phone { get; set; }
        public string order_address { get; set; }
        public string order_email { get; set; }
        public string order_fname { get; set; }
        public string order_lname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Item> Order_Item { get; set; }
        public virtual User User { get; set; }
    }
}
